version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ./data:/var/lib/rabbitmq
    restart: always

  server:
    build:
      context: ../server
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
    command: ["sh", "-c", "sleep 5 && ./server"]
    restart: always

  client:
    build:
      context: ../client
      dockerfile: Dockerfile
    depends_on:
      - server
    environment:
      RABBITMQ_HOST: rabbitmq
    command: ["sh", "-c", "sleep 10 && ./client"]
    restart: always
